# Generated by Django 5.2.10 on 2026-01-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_auditlog_mfarecoverycode"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_fallback_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="primary_mfa_method",
            field=models.CharField(
                choices=[("totp", "Authenticator (TOTP)"), ("email", "Email OTP")],
                default="totp",
                max_length=10,
            ),
        ),
    ]
