# Generated by Django 5.2.10 on 2026-01-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_alter_auditlog_options_remove_auditlog_ip_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_change_token_jti",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_change_token_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
