# Generated by Django 6.0.1 on 2026-02-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_userprofile_email_change_token_jti_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="theme_preference",
            field=models.CharField(
                choices=[("system", "System"), ("light", "Light"), ("dark", "Dark")],
                default="system",
                max_length=10,
            ),
        ),
    ]
