# Generated by Django 6.0.1 on 2026-02-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_userprofile_theme_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_change_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pending_new_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
