# Generated by Django 6.0.1 on 2026-02-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_userprofile_email_change_requested_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="pending_new_email",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_change_pending_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
