# Generated by Django 6.0.1 on 2026-02-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0010_remove_userprofile_pending_new_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_superadmin",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
