# Generated by Django 6.0.1 on 2026-02-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0011_userprofile_is_superadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("suspended", "Suspended"),
                    ("pending", "Pending Verification"),
                ],
                db_index=True,
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="status_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="suspended_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
